application: thebuzzengine2
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /api/.*
  script: main.app

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /(.*)
  static_files: static/\1
  upload: static/

libraries:
- name: django
  version: "1.4"
