application: thebuzzengine
version: 1
runtime: python
api_version: 1

default_expiration: "30d"

builtins: 
- remote_api: on 
- datastore_admin: on 

inbound_services:
- mail

handlers:

- url: /crossdomain.xml
  static_files: buzzengine/static/load-policy.xml
  upload:  buzzengine/static/load-policy.xml

- url: /favicon.ico
  static_files: buzzengine/static/images/favicon.ico
  upload:  buzzengine/static/images/favicon.ico

- url: /static
  static_dir: buzzengine/static  

- url: /_ah/mail/.+ 
  script: buzzengine/email_handler.py 
  login: admin

- url: /.*
  script: buzzengine/handler.py

