application: thebuzzengine
version: 1
runtime: python
api_version: 1

default_expiration: "30d"

builtins:

- datastore_admin: on

handlers:

- url: /crossdomain.xml
  static_files: buzzengine/static/load-policy.xml
  upload:  buzzengine/static/load-policy.xml

- url: /static
  static_dir: buzzengine/static  

- url: /.*
  script: buzzengine/handler.py

